version: 2
jobs:
  build:
    docker:
      - image: yukimemi/zola-blog

    steps:
      - checkout

      - run:
          name: Update apt
          command: apt update

      - run:
          name: Install zip and curl
          command: apt install -y zip curl

      - run:
          name: Git clone theme
          command: git clone https://github.com/getzola/even themes/even

      - run:
          name: Which zola
          command: which zola

      - run:
          name: Build with zola
          command: zola build

      - run:
          name: Zip public site
          command: zip -r public.zip public

      - run:
          name: Deploy site
          command: 'curl -H "Content-Type: application/zip" -H "Authorization: Bearer ${NETLIFY_TOKEN}" --data-binary "@public.zip" https://api.netlify.com/api/v1/sites/yukimemi.netlify.com/deploys'
